save_dir: ./saved_models
save_name: uda_voc12_1323_0
resume: False
load_path: None
overwrite: True
use_tensorboard: True
epoch: 1
# 262144, 2000000?
num_train_iter: 262144
num_eval_iter: 2000
num_labels: 1323
batch_size: 16
eval_batch_size: 64
TSA_schedule: none
T: 0.4
p_cutoff: 0.8
ulb_loss_ratio: 1.0
uratio: 7
ema_m: 0.999
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
amp: False
net: ResNet50
net_from_name: False
depth: 0
widen_factor: 0
leaky_slope: 0.1
dropout: 0.0
data_dir: ../../dataset/VOC/
dataset: voc12
train_sampler: RandomSampler
num_classes: 20
num_workers: 1
alg: uda
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10014
dist_backend: nccl
gpu: None
